# for an example project named 'helloworld'

steps:
    # build the container images
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/coflix-402007/helloworld', './client']

    # push the container images to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/coflix-402007/helloworld']

    # Deploy container images to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'run',
              'deploy',
              'helloworld',
              '--image',
              'gcr.io/coflix-402007/helloworld',
              '--region',
              'asia-northeast3',
              '--platform',
              'managed',
              '--quiet',
              '--allow-unauthenticated',
          ]
images:
    - gcr.io/coflix-402007/helloworld
# steps:
#     # 1. Node.js 애플리케이션 빌드 단계
#     - name: 'gcr.io/cloud-builders/npm'
#       args: ['install']
#     - name: 'gcr.io/cloud-builders/npm'
#       args: ['run', 'build']

#     # 2. Cloud Functions 배포 단계
#     - name: 'gcr.io/cloud-builders/gcloud'
#       args:
#           [
#               'functions',
#               'deploy',
#               'my-function',
#               '--runtime=nodejs18',
#               '--trigger-http',
#           ]

# # 이미지 빌드와 배포를 위한 설정
# images: ['gcr.io/coflix-402007/helloworld']
