steps:
    # 1. Node.js 애플리케이션 빌드 단계
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']

    # 2. Docker 이미지 빌드 단계
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/coflix-402007/helloworld', '.']

    # 3. Google Cloud Run 배포 단계
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          - 'run'
          - 'deploy'
          - '--image=gcr.io/coflix-402007/helloworld'
          - '--project=coflix-402007'
          - '--platform=managed'
          - '--region=asia-northeast3' # 원하는 지역 설정
          - '--allow-unauthenticated' # 필요한 경우 인증 생략

images: ['gcr.io/coflix-402007/helloworld']
